name: Push NuGet to JFrog

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'      

defaults:
  run:
    working-directory: ./CustomLibrary
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0 # adjust as needed
      
      - name: Get nuspec version
        id: getnuspecVersion
        shell: pwsh
        run: |
            cd ./Package
            [xml]$xml = Get-Content My.Spec.nuspec
            $version = $xml.package.metadata.version
            "nuspecVersion=$version" >> $env:GITHUB_OUTPUT

      - name: Get version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            # If it's a tag push, strip 'refs/tags/' to get tag
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            # If not a tag, use branch name + short SHA as version
            VERSION="0.0.${GITHUB_RUN_NUMBER}"
          fi
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release /p:Version=${{ steps.version.outputs.version }}

      - name: Pack NuGet package
        run: dotnet pack --configuration Release /p:Version=${{ steps.version.outputs.version }}

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JFROG_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
          
      - name: Publish to Artifactory
        run: |
          jf rt u "**/*.nupkg" custompackages2/ --flat=true
